INPUTS:
   - "af"
   - "AJAHR"
   - "ALTER1"
   - "ENTSCH"
   - "f"
   - "JFREIB"
   - "JHINZU"
   - "JRE4"
   - "JVBEZ"
   - "KRV"
   - "KVZ"
   - "LZZ"
   - "LZZFREIB"
   - "LZZHINZU"
   - "MBV"
   - "PKPV"
   - "PKV"
   - "PVS"
   - "PVZ"
   - "R"
   - "RE4"
   - "SONSTB"
   - "STERBE"
   - "STKL"
   - "VBEZ"
   - "VBEZM"
   - "VBEZS"
   - "VBS"
   - "VJAHR"
   - "VKAPA"
   - "VMT"
   - "ZKF"
   - "ZMVB"
   - "JRE4ENT"
   - "SONSTENT"
OUTPUTS:
  - "BK"
  - "BKS"
  - "BKV"
  - "LSTLZZ"
  - "SOLZLZZ"
  - "SOLZS"
  - "SOLZV"
  - "STS"
  - "STV"
  - "VKVLZZ"
  - "VKVSONST"
  - "VFRB"
  - "VFRBS1"
  - "VFRBS2"
  - "WVFRB"
  - "WVFRBO"
  - "WVFRBM"
INTERNALS:
  - "ALTE"
  - "ANP"
  - "ANTEIL1"
  - "BMG"
  - "BBGKVPV"
  - "bd"
  - "BBGRV"
  - "DIFF"
  - "EFA"
  - "FVB"
  - "FVBSO"
  - "FVBZ"
  - "FVBZSO"
  - "GFB"
  - "HBALTE"
  - "HFVB"
  - "HFVBZ"
  - "HFVBZSO"
  - "J"
  - "JBMG"
  - "JLFREIB"
  - "JLHINZU"
  - "JW"
  - "K"
  - "KENNVMT"
  - "KFB"
  - "KVSATZAG"
  - "KVSATZAN"
  - "KZTAB"
  - "LSTJAHR"
  - "LST1"
  - "LST2"
  - "LST3"
  - "LSTOSO"
  - "LSTSO"
  - "MIST"
  - "PVSATZAG"
  - "PVSATZAN"
  - "RVSATZAN"
  - "RW"
  - "SAP"
  - "SOLZFREI"
  - "SOLZJ"
  - "SOLZMIN"
  - "SOLZSBMG"
  - "SOLZSZVE"
  - "SOLZVBMG"
  - "ST"
  - "ST1"
  - "ST2"
  - "STOVMT"
  - "TBSVORV"
  - "VBEZB"
  - "VBEZBSO"
  - "VHB"
  - "VSP"
  - "VSPN"
  - "VSP1"
  - "VSP2"
  - "VSP3"
  - "W1STKL5"
  - "W2STKL5"
  - "W3STKL5"
  - "VSPMAX1"
  - "VSPMAX2"
  - "VSPO"
  - "VSPREST"
  - "VSPVOR"
  - "X"
  - "Y"
  - "ZRE4"
  - "ZRE4J"
  - "ZRE4VP"
  - "ZTABFB"
  - "ZVBEZ"
  - "ZVBEZJ"
  - "ZVE"
  - "ZX"
  - "ZZX"
  - "HOCH"
  - "VERGL"
  - "VKV"
