FACTS: []
INPUTS:
  AJAHR: 0.0
  ALTER1: 0.0
  ENTSCH: 0.0
  JFREIB: 0.0
  JHINZU: 0.0
  JRE4: 0.0
  JRE4ENT: 0.0
  JVBEZ: 0.0
  KRV: 0.0
  KVZ: 0.0
  LZZ: 0.0
  LZZFREIB: 0.0
  LZZHINZU: 0.0
  MBV: 0.0
  PKPV: 0.0
  PKV: 0.0
  PVS: 0.0
  PVZ: 0.0
  R: 0.0
  RE4: 0.0
  SONSTB: 0.0
  SONSTENT: 0.0
  STERBE: 0.0
  STKL: 0.0
  VBEZ: 0.0
  VBEZM: 0.0
  VBEZS: 0.0
  VBS: 0.0
  VJAHR: 0.0
  VKAPA: 0.0
  VMT: 0.0
  ZKF: 0.0
  ZMVB: 0.0
  af: 0.0
  f: 0.0
INTERNALS:
  ALTE: 0.0
  ANP: 0.0
  ANTEIL1: 0.0
  BBGKVPV: 0.0
  BBGRV: 0.0
  BMG: 0.0
  DIFF: 0.0
  EFA: 0.0
  FVB: 0.0
  FVBSO: 0.0
  FVBZ: 0.0
  FVBZSO: 0.0
  GFB: 0.0
  HBALTE: 0.0
  HFVB: 0.0
  HFVBZ: 0.0
  HFVBZSO: 0.0
  HOCH: 0.0
  J: 0.0
  JBMG: 0.0
  JLFREIB: 0.0
  JLHINZU: 0.0
  JW: 0.0
  K: 0.0
  KENNVMT: 0.0
  KFB: 0.0
  KVSATZAG: 0.0
  KVSATZAN: 0.0
  KZTAB: 0.0
  LST1: 0.0
  LST2: 0.0
  LST3: 0.0
  LSTJAHR: 0.0
  LSTOSO: 0.0
  LSTSO: 0.0
  MIST: 0.0
  PVSATZAG: 0.0
  PVSATZAN: 0.0
  RVSATZAN: 0.0
  RW: 0.0
  SAP: 0.0
  SOLZFREI: 0.0
  SOLZJ: 0.0
  SOLZMIN: 0.0
  SOLZSBMG: 0.0
  SOLZSZVE: 0.0
  SOLZVBMG: 0.0
  ST: 0.0
  ST1: 0.0
  ST2: 0.0
  STOVMT: 0.0
  TBSVORV: 0.0
  VBEZB: 0.0
  VBEZBSO: 0.0
  VERGL: 0.0
  VHB: 0.0
  VKV: 0.0
  VSP: 0.0
  VSP1: 0.0
  VSP2: 0.0
  VSP3: 0.0
  VSPMAX1: 0.0
  VSPMAX2: 0.0
  VSPN: 0.0
  VSPO: 0.0
  VSPREST: 0.0
  VSPVOR: 0.0
  W1STKL5: 0.0
  W2STKL5: 0.0
  W3STKL5: 0.0
  X: 0.0
  Y: 0.0
  ZRE4: 0.0
  ZRE4J: 0.0
  ZRE4VP: 0.0
  ZTABFB: 0.0
  ZVBEZ: 0.0
  ZVBEZJ: 0.0
  ZVE: 0.0
  ZX: 0.0
  ZZX: 0.0
  bd: 0.0
OUTPUTS:
  BK: 0.0
  BKS: 0.0
  BKV: 0.0
  LSTLZZ: 0.0
  SOLZLZZ: 0.0
  SOLZS: 0.0
  SOLZV: 0.0
  STS: 0.0
  STV: 0.0
  VFRB: 0.0
  VFRBS1: 0.0
  VFRBS2: 0.0
  VKVLZZ: 0.0
  VKVSONST: 0.0
  WVFRB: 0.0
  WVFRBM: 0.0
  WVFRBO: 0.0
